# Generated by Django 4.0.3 on 2022-04-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wanted_gogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funding',
            old_name='decription',
            new_name='description',
        ),
    ]
