# Generated by Django 4.0.3 on 2022-04-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted_gogo', '0002_rename_decription_funding_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='funding',
            name='session_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='funding',
            name='target_price',
            field=models.IntegerField(null=True),
        ),
    ]
